language: java
jdk:
  - oraclejdk8
  - openjdk8

# install: true

cache:
  directories:
  - "$HOME/.cache"

script:
  - mvn -X
  - mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
