language: java
jdk:
  - oraclejdk8
  - openjdk8

# install: true

cache:
  directories:
  - "$HOME/.cache"

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn clean verify
  - mvn -X
  - mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
